name: Generate WireGuard Config

on:
  schedule:
    - cron: "0 */5 * * *" # каждые 5 часов
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wireguard-tools jq curl qrencode

      - name: Run generator
        run: |
          chmod +x ./generator.sh
          ./generator.sh

      - name: Commit and push warp.conf
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add warp.conf
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update WireGuard config [$(date -u)]"
            git push https://$GH_PAT@github.com/readyforread/Wireguard.git HEAD:main
