name: Generate WireGuard Config

on:
  schedule:
    - cron: "0 */5 * * *" # каждые 5 часов
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wireguard-tools jq curl qrencode

      - name: Generate WireGuard config
        run: |
          set -e
          PRIV="${1:-$(wg genkey)}"
          PUB="${2:-$(echo "$PRIV" | wg pubkey)}"
          API="https://api.cloudflareclient.com/v0i1909051800"
          ins() { curl -s -H 'user-agent:' -H 'content-type: application/json' -X "$1" "${API}/$2" "${@:3}"; }
          sec() { ins "$1" "$2" -H "authorization: Bearer $3" "${@:4}"; }
          RESPONSE=$(ins POST "reg" -d "{\"install_id\":\"\",\"tos\":\"$(date -u +%FT%T.000Z)\",\"key\":\"$PUB\",\"fcm_token\":\"\",\"type\":\"ios\",\"locale\":\"en_US\"}")
          ID=$(echo "$RESPONSE" | jq -r '.result.id')
          TOKEN=$(echo "$RESPONSE" | jq -r '.result.token')
          RESPONSE=$(sec PATCH "reg/$ID" "$TOKEN" -d '{"warp_enabled":true}')
          PEER_PUB=$(echo "$RESPONSE" | jq -r '.result.config.peers[0].public_key')
          IPV4=$(echo "$RESPONSE" | jq -r '.result.config.interface.addresses.v4')
          IPV6=$(echo "$RESPONSE" | jq -r '.result.config.interface.addresses.v6')

          # Генерация конфигурационного файла
          cat > warp.conf <<EOF
[Interface]
PrivateKey = $PRIV
Address = $IPV4, $IPV6
DNS = 1.1.1.1, 2606:4700:4700::1111, 1.0.0.1, 2606:4700:4700::1001
MTU = 1280

[Peer]
PublicKey = $PEER_PUB
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 162.159.192.1:500
EOF

          echo "✅ Конфиг сохранён в warp.conf"

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add warp.conf
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update WireGuard config [$(date -u)]"
            git push https://$GH_PAT@github.com/<ТВОЙ_НИК>/<РЕПО>.git HEAD:main
