
name: Generate WireGuard Config

on:
  schedule:
    - cron: "0 */12 * * *"   # каждые 12 часов
  workflow_dispatch:         # возможность запускать вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y qrencode

      - name: Download warp generator
        run: curl -o warp_generator.sh https://raw.githubusercontent.com/ImMALWARE/bash-warp-generator/main/warp_generator.sh

      - name: Make generator executable
        run: chmod +x warp_generator.sh

      - name: Generate config
        run: ./warp_generator.sh > warp.conf

      - name: Commit and push new config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add warp.conf
          git commit -m "Update WireGuard config [$(date)]" || echo "No changes"
          git push
