name: Update WireGuard Config

on:
  schedule:
    - cron: '0 */5 * * *'  # Каждые 5 часов
  workflow_dispatch:      # Позволяет запускать вручную

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wireguard-tools jq curl qrencode

      - name: Generate WireGuard config
        run: |
          #!/bin/bash
          set -e
          priv="${1:-$(wg genkey)}"
          pub="${2:-$(echo "${priv}" | wg pubkey)}"
          api="https://api.cloudflareclient.com/v0i1909051800"
          ins() { curl -s -H 'user-agent:' -H 'content-type: application/json' -X "$1" "${api}/$2" "${@:3}"; }
          sec() { ins "$1" "$2" -H "authorization: Bearer $3" "${@:4}"; }
          response=$(ins POST "reg" -d "{\"install_id\":\"\",\"tos\":\"$(date -u +%FT%T.000Z)\",\"key\":\"${pub}\",\"fcm_token\":\"\",\"type\":\"ios\",\"locale\":\"en_US\"}")
          id=$(echo "$response" | jq -r '.result.id')
          token=$(echo "$response" | jq -r '.result.token')
          response=$(sec PATCH "reg/${id}" "$token" -d '{"warp_enabled":true}')
          peer_pub=$(echo "$response" | jq -r '.result.config.peers[0].public_key')
          client_ipv4=$(echo "$response" | jq -r '.result.config.interface.addresses.v4')
          client_ipv6=$(echo "$response" | jq -r '.result.config.interface.addresses.v6')
          conf=$(cat <<EOM
[Interface]
PrivateKey = ${priv}
Address = ${client_ipv4}, ${client_ipv6}
DNS = 1.1.1.1, 2606:4700:4700::1111, 1.0.0.1, 2606:4700:4700::1001
MTU = 1280

[Peer]
PublicKey = ${peer_pub}
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 162.159.192.1:500
EOM
)
          echo "$conf" > warp.conf
          echo "✅ Конфиг сохранён в warp.conf"

      - name: Commit and push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add warp.conf
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update WireGuard config [$(date -u)]"
            git push https://$GH_PAT@github.com/readydorread/Wireguard.git HEAD:main
          fi
