name: Generate WireGuard Config

on:
  schedule:
    - cron: "0 */5 * * *" # каждые 5 часов
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wireguard-tools jq curl qrencode

      - name: Run generator
        run: |
          chmod +x ./generator.sh
          ./generator.sh

      - name: Commit and push warp.conf
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          # Настраиваем git
          git config --global user.name "readyforread"
          git config --global user.email "arm2000arms@gmail.com"

          # Проверка токена
          git ls-remote https://$GH_PAT@github.com/readyforread/Wireguard.git || exit 1

          # Добавляем изменения
          git add warp.conf

          # Коммитим только если есть изменения
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            COMMIT_MSG="Update WireGuard config [$(date -u +'%Y-%m-%d %H:%M:%S')]"
            git commit -m "$COMMIT_MSG"
            git push https://$GH_PAT@github.com/readyforread/Wireguard.git HEAD:main
          fi
